# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Box Settings
  config.vm.box = "ubuntu/trusty64"
  
  # Provider Settings
	config.vm.provider "virtualbox" do |vb|
		vb.memory = 512
  
	end
  
  # Network Settings

  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"


  # Folder Settings
  # config.vm.synced_folder "../data", "/vagrant_data"
	

  


  # Provision Settings
   config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
     
     #sudo apt-get install -y ufw
     #sudo ufw enable
     #sudo ufw allow 80/tcp
     #sudo ufw allow from any to any port 22
     #sudo ufw allow out 22/tcp

     #sudo apt-get install libapache2-mod-proxy-html
     #sudo apt-get install libxml2-dev

     #sudo a2enmod proxy
     #sudo a2enmod proxy_html
     #sudo a2enmod proxy_http

     #sudo service apache2 restart
     


     
   SHELL
   
   # config.vm.provision "shell", path: "bootstrap.sh"
end
